swagger: "2.0"

info:
  version: 1.0.0
  title: API
  description: |
    API description

schemes:
  - http
  - https

host: localhost:3002
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json

paths:
  /palindrome/stats:
    x-swagger-router-controller: palindrome
    get:
      operationId: getAllStats
      summary: Get all palindrome stats
      tags:
        - Palindrome
      responses:
        200:
          description: Default response
          schema:
            type: array
            items:
              type: object
              properties:
                _id:
                  type: integer
                  format: int64
                sentence:
                  type: string
                timestamp:
                  type: string
                isValid:
                  type: boolean
                count:
                  type: number

  /palindrome/check:
    x-swagger-router-controller: palindrome
    post:
      operationId: check
      summary: Make a check if the given sentence is palindrome
      tags:
        - Palindrome
      parameters:
        - in: body
          name: body
          required: true
          schema:
            # Body schema with atomic property examples
            type: object
            properties:
              sentence:
                type: string
                example: "level"
                description: Sentence to be check if it is palindrome
      responses:
        200:
          description: Default response
          schema:
            type: boolean

  /dictionary/check:
    x-swagger-router-controller: dictionary
    post:
      operationId: check
      summary: Make a check if the given word or sentence is dictionary valid
      tags:
        - Dictionary
      parameters:
        - in: body
          name: body
          required: true
          schema:
            # Body schema with atomic property examples
            type: object
            properties:
              sentence:
                type: string
                example: "race car"
                description: Sentence or word
      responses:
        200:
          description: Default response
          schema:
            type: boolean
